apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- behavior: merge
  files:
  - kleat/clouddriver.yml
  name: clouddriver-config
- behavior: merge
  files:
  - kleat/settings.js
  name: deck-config
- behavior: merge
  files:
  - kleat/echo.yml
  name: echo-config
- behavior: merge
  files:
  - kleat/fiat.yml
  name: fiat-config
- behavior: merge
  files:
  - kleat/front50.yml
  name: front50-config
- behavior: merge
  files:
  - kleat/gate.yml
  name: gate-config
- behavior: merge
  files:
  - kleat/igor.yml
  name: igor-config
- behavior: merge
  files:
  - kleat/kayenta.yml
  name: kayenta-config
- behavior: merge
  files:
  - kleat/orca.yml
  name: orca-config
- behavior: merge
  files:
  - kleat/rosco.yml
  name: rosco-config
- behavior: merge
  name: spinnaker-monitoring-config
  files:
  - kleat/spinnaker-monitoring.yml
- behavior: merge
  name: spinnaker-monitoring-filters
  files: []
- behavior: merge
  name: spinnaker-secrets
  files: []
configMapGenerator:
- behavior: merge
  name: deck-env
  envs:
  - kleat/deck.env
resources:
- github.com/spinnaker/kustomization-base/core
# - github.com/spinnaker/kustomization-base/kayenta
# - github.com/spinnaker/kustomization-base/fiat
commonLabels:
  app.kubernetes.io/component: server
  app.kubernetes.io/managed-by: kleat
  app.kubernetes.io/part-of: spinnaker
  app.kubernetes.io/version: spinnaker-master-latest-unvalidated
namespace: spinnaker
images:
- name: gcr.io/spinnaker-marketplace/clouddriver
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/deck
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/echo
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/fiat
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/front50
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/gate
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/igor
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/kayenta
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/monitoring-daemon
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/orca
  newTag: spinnaker-master-latest-unvalidated
- name: gcr.io/spinnaker-marketplace/rosco
  newTag: spinnaker-master-latest-unvalidated
