apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- behavior: merge
  files:
  - kleat/clouddriver.yml
  name: clouddriver-config
- behavior: merge
  files:
  - kleat/echo.yml
  name: echo-config
- behavior: merge
  files:
  - kleat/front50.yml
  name: front50-config
- behavior: merge
  name: spinnaker-secrets
resources:
- github.com/spinnaker/kustomization-base/base
